### ISSUE TITLE
Issue with the character count?

### ISSUE THREAD

**Issue by drCosmar** [chegele/ValheimManager#13]
```
What is the id of your servers admin/mod role?
 > 1104XXX791321XXXXXX

There was an error processing that response - A discord id is expected to be 18 characters long.
What is the id of your servers admin/mod role?
```

I am positive I am gathering the right data. It has 19 characters, not 18 though.
![image](https://github.com/chegele/ValheimManager/assets/56284390/25e19aeb-699a-474b-ad3e-4626dd916984)

General feedback as a user from here:
The issue with grammar. Possessive pronouns need a '. Otherwise, if English is your second language, you may read the question all wrong. "What is the id of your servers (plural) admin/mod role?". Not reality-breaking, but it's just one example I've seen so far.

There is also the wording and the lack of instruction. I imagine this is more intended for power users but consider enlisting AI's help to compile instructions if you find them tedious or annoying.

Thanks for the hard work.

**Comment by chegele** [comment]
You should now be able to successfully configure your discord server and admin roles. 

I will look into addressing the grammar mistakes in a future update. 

Regarding the lack of instruction, could you provide specifics about what you would like to see documented? As the developer is it hard to know what may not be intuitive to other users. I would be happy to compile some more instructions for the tool.

Thank you for your feedback! Please feel free to reach out with any other issues, questions, or feature requests.

**Comment by drCosmar** [comment]
Most individuals will never turn on their developer mode.

Perhaps preface your instructions with the prerequisites is what I mean. Not really so much as it needs more instructions, per se, maybe just a set-up checklist before you follow the installation instruction.

- Specifically;
1. Explain to or show the user how to turn on developer mode, or provide a link with valid instructions.
2. Show the user how to obtain ID keys. It might sound simple, and it was. It was by no means intuitive though.

If you are familiar with creating discord bots, it would be a no-brainer. This would be my first one, so I had to struggle to figure out how to get access to the ID, then I had to figure out how to actually copy the ID. Cost about 30 mins, but I'm inefficient lol.

I went ahead and used AI to help generate something a little more information-dense;

```
Pre-requisites:
1. Turn on Discord developer mode:
   - On the website or desktop app:
     - Click the gear icon in the bottom-left corner (next to your name), then select Advanced from the left sidebar.
     - At the top of the page that appears, toggle on Developer Mode.
   - On the mobile app:
     - For iOS: Swipe to the right to open the navigation menu, then tap your profile picture in the bottom-right corner. In the iPhone app, scroll down and tap Appearance, then toggle on Developer Mode. 
     - For Android: Swipe to the right to open the navigation menu, then tap your profile picture in the bottom-right corner. In the Android app, swipe down and tap Behavior, then toggle on Developer Mode.


Valheim Manager Setup:
1. Run the command: npm install -g valheim-manager
2. Launch the tool with the command: valheim-manager
3. To save time on future launches, navigate to the location where you saved your configuration before starting the Valheim Manager:
   'cd C:\Users\scheg\Documents\ValheimManager\
   valheim-manager'

Discord Bot Setup:
1. Create a new discord application: https://discord.com/developers/applications
2. Generate the bot token and take note of it.
3. Invite the bot to your discord server by using the link below (replace INSERT_CLIENT_ID_HERE with your id)
4. Gather your discord ids by right-clicking items in Discord and selecting "Copy Id":
   - Discord server id - Right-click the server icon in the left sidebar.
   - Admin/mod role - Right-click the admin role in the role list.
   - Server log channel - Right-click the server log channel.
   - Command log channel - Right-click the command log channel.
```

A lot of that for me or you are self-explanatory, but half the battle is getting people to use what you put effort into making. Keeping everything in the Readme just makes it easier for everyone who wants to try and use it. If the instructions all come from one place, it's one less variable to troubleshoot.

It's still missing a few things too, but all I did was tell phind.com "Can you take the readme from this GitHub repository and add the following prerequisites, and surround it in a codeblock so I can copy it?", it came up with that. Mileage may very, but it's gotten pretty used to knowing what I want.

**Comment by drCosmar** [comment]
You also still have an issue regarding character count.
Same issue as above.

I wish I could be of more help, but my expertise is in Python, D, and Proompt engineering. Don't even know what I'm looking for regarding javascript, much less node.

I think I will attempt to do this in Python though, was the original plan.

I wish you all the lucks and figgy pudding.

**Comment by chegele** [comment]
You may still need to update your manager. 

`npm update -g`
