### ISSUE TITLE
v1.2.0 not accepting 18 or 19 discord character length

### ISSUE THREAD

**Issue by zem-sessions** [chegele/ValheimManager#18]
installed v1.2.0

I get to the step where it asks for a discord bot, and when putting in the discord id: "There was an error processing that response - A discord id is expected to be 18 characters or longer."

The error appears whether I provide an 18 or 19 digit length.

**Comment by chegele** [comment]
Patch 1.2.1 for this issue. Please let me know if you continue to see problems.
